x = input('Digite algo: ')
print('O tipo primitivo é: ', type(x))
print(x, 'é número?', x.isnumeric())
print(x, 'é letra?', x.isalpha())
print(x, 'esta em maiusculo?', x.isupper())
print(x, 'esta em minusculo?', x.islower())
print(x, 'so tem espacos?', x.isspace())
print(x, 'é alfanumerico?', x.isalnum())
print(x,'esta capitalizado?', x.istitle())
